### PR TITLE
Updated ncsim Makefile. Minor corrections to source and testbench files

### PR DESCRIPTION
**Pull request by dgarigali**

### CODE REVIEW

**Comment by jjts** [comment]
Will merge but testbench should be self-checking (compare with expected response)

**Comment by dgarigali** [comment]
> Will merge but testbench should be self-checking (compare with expected response)

Ok, in the near future I will update all testbenches to be self-checking

**Comment by jjts** [comment]
Be careful. Start with the ones you truly need; leave a note on those that
need to be updated but don't necessarily do them.



Com os melhores cumprimentos / Best regards,

Jose T. de Sousa

**Comment by dgarigali** [comment]
Ok, I will do that for the next PR

**Pull request merged**
